site_name: Memorabilia
site_url: https://mydomain.org/mysite
site_author: zshao0227
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown # 主色
      accent: brown # 强调色 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      #primary: black
      #accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features: 
    - announce.dismiss # 可关闭公告栏
    - navigation.instant # 页面无刷新切换
    - navigation.prune # 只渲染可见导航项
    # - header.autohide  # 自动隐藏头部
    - navigation.instant.progress # 页面切换进度条
    #- navigation.prune # 只渲染可见导航项
    - navigation.tracking # 滚动时URL锚点自动更新
    - navigation.tabs # 一级导航显示为顶部Tab
    # - navigation.tabs.sticky  # Tab栏吸顶
    #- navigation.sections # 侧边栏分组
    - navigation.top # 返回顶部按钮
    - navigation.footer # 页脚显示在侧边栏
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索结果分享
    - toc.follow # 目录跟随滚动
    #- toc.integrate # 目录集成到侧边栏
    - navigation.expand # 默认展开所有目录
    - navigation.indexes # 支持节索引页
    - content.tabs.link # 支持标签页链接
    - content.tooltips # 支持鼠标悬浮提示
    - content.code.copy # 代码块一键复制
    - content.code.select # 代码块一键全选
    # - content.action.edit # 编辑按钮
    # - content.action.view # 查看源码按钮
    - content.code.annotate # 代码注释
  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/zshao0227/IHOC # 右上角点击跳转的链接
repo_name: zshao0227/IHOC # 右上角的名字

nav:
  # - 主页: /
  - History of the Internet:
    - China:
      - Booting Up: china/1.md
      - Awaiting Scale: china/2.md
      - Cat and Mouse Era: china/3.md
      - Nailing Jell-O to the Wall: china/4.md
      - China’s Own Innovations: china/5.md
      - What’s Next?: china/6.md
    - America: america.md

plugins:
  - search


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:  
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      # baselevel: 2
      # toc_depth: 3  # 控制标题层级深度
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - neoteroi.timeline